---
title: 'Lesson 06: The review'
output:
  html_document:
    df_print: paged
---

## Problem 1: the magician strikes back

Assume that a person is claiming to have paranormal abilities. To test these abilities, we perform the following experiment. There is a box with one red and two blue balls. The balls are identical in every aspect but color. An assistant shuffles the box, picks a ball from it randomly, then record its color and return the ball to the box. This process is repeated several times. The magician tries to guess the result of these pickings (the more the better).

### The best strategy
What is the best strategy for the magician if he actually doesn't have magicial abilities?

*Answer*: say "blue" every time.

### The model
Assume that we pick a ball 12 times, the magician actually doesn't have magical abilities and just use the best strategy described above. Denote the number of correct guesses by $X$. State how can we obtain $X$ in terms of coin-tossing? 

#### Answer
Consider guessing of the result of one ball-picking. The outcome of this guessing is either "guessed correctly" or "made a mistake". If the magician just uses strategy _say 'blue' every time_, then probability of outcome "guessed correctly" is 2/3. Therefore, we can replace this "guessing of the result of one ball-picking" with one coin-tossing.

Consider a special coin with words "guessed correctly" on one side and "made a mistake" on the other side. Assume it's a "loaded" coin, i.e. not fair: probability to land with words "guessed correctly" on top is 2/3.

Then the outcome of one tossing of such a coin is the same as the outcome of one guessing the result of ball-picking (provided that the magician uses strategy _say 'blue' every time_).

To simulate guessing the result of 12 ball-pickings, we can toss a coin 12 times. Number of correct guesses is equivalent to the number of cases when we have "guessed correctly" on top side of a coin. This is our number $X$.

Finally, we can replace our very special with a bit more ordinary coin: assume that we have head and tail as usual, but probability to obtain "head" is 2/3. Then we toss this coin 12 times and count how many "heads" we had. This is $X$. 

### Hypothesis
State your null hypothesis and an alternative in terms of the original question and in terms of the coin-tossing model.

#### In terms of the original question
$H_0$: The magician doesn't have magical abilities and uses strategy _say 'blue' every time_.

$H_1$: The magician has magical abilities, that allow him to guess correct answer more frequently that with the best strategy known to mere mortals (i.e. _say 'blue' every time_).

#### In terms of coin-tossing model
In section [the model](#The model) above, we discussed that if there are no magical abilities and the magician uses best available strategy, the result of one guessing is equivalent to result of one coin-tossing with probability of success (i.e. "head" or "guessed correctly") equal to 2/3. However, if he has magical abilities, then this probability would be larger.

Let us consider a coin that lands with "head" with probability $p$. Then our null hypothesis and alternative are stated as follows:

$H_0$: $p=2/3$.

$H_1$: $p>2/3$.

Note that any $p$ that is larger then theoretically possible $2/3$ constitute violation of null hypothesis: i.e. even if the magician can predict correct result with probability $2/3 + 0.000000001$, he still a magician.

### Decision rule
Assume that the organizers would claim that the magician actually have magical abilities (i.e. reject null hypothesis) if he guesses 12 times out of 12, otherwise they will not claim that he has magical abilities (do not reject null hypothesis). Assume that the magician doesn't have magical abilities and follows the best strategy (thus null hypothesis is true). What is the probability to make type I error? Type II error?

#### Recall

Type I error: reject null hypothesis while it is true.

Type II error: not reject null hypothesis while null hypothesis is false.

#### Answer
As we assume that null hypothesis holds, every time we reject it, we make type I error.

Thus

$$
\begin{multline}
P(\text{type I error}) = P(\text{reject null hypothesis}) = \\
=P(\text{claim he is actually a magician}) = P(\text{guess 12 out of 12}) =\\
=P((2/3)^{12}) = 0.007707347
\end{multline}
$$

It is not possible to make type II error in this case as we assume that null hypothesis holds, and type II error can be made only in case null hypothesis does not hold.

## Type II errors
Assume that $p=3/4$ and thus $H_0$ is violated. We use the same decision rule as previously.

Which error (type I, type II) can we make? Find corresponding probabilities.

### Decision rule
Assume that we claim that the person has magical abilities if he guesses $X_{crit}$ times or more. Find the smallest value of $X_{crit}$ such that probability to make type I error is less than 0.05.

### p-value
Assume that the magician guessed 10 times out of 12. Find the corresponding p-value. Would you reject null hypothesis, i.e. claim that the magician has magical abilities?

## Problem 2: the magician and the mean
Now the magician claims that he has psychokinetic abilities. To test it, we perform the following experiment. We have a box with five balls, each ball has a number on it: 1, 3, 4, 7, 8. Again we select random ball, record the number, then put the ball again in the box, and repeat the process several times. Thus we obtain a sample of numbers. The magician uses his abilities to make average of these numbers to be as large as possible.

### Population mean
Find population mean, i.e. average of numbers in the box.

### Sample mean vs. population mean
Assume that at some experiment we obtained the following sample: 8, 3, 3, 1, 1, 7, 8, 7. Its mean (find it) is larger than the population mean. The magician says:

> Now you see? I has psychokinetic abilities! I said I will increase the mean and it is indeed larger than the population mean.

Does it look convincing?

### More results
Assume that you obtained sample mean that is equal to 8 and your sample size is 5. Does it look convincing now?

### Hypotheses
State null hypothesis and an alternative in this experiment.

### The decision rule
As the magician claims that he is trying to make the sample mean as large as possible, we use the following decision rule: we choose some value $\bar x_{crit}$ and will claim that the magician has magical abilities if sample average is equal to $\bar x_{crit}$ or larger. Let $\bar x_{crit}=7$. Assume that the magician doesn't have magical abilities. Simulate 10000 sampling from our box, sample size = 5. How many times would you reject null hypothesis, i.e. claim that the magician indeed has magical abilities?

### Average distribution
Plot the distribution of $\bar x$ for the previous subproblem.

### Rejection region
Find such smallest value $\bar x_{crit}$ that if you use this, the probability to make type I error would be less than 0.05. Use `quantile` function.

### p-value
Assume that we obtained the following data: 7, 8, 4, 8, 8. Find the corresponding p-value. Would you reject null hypothesis?
